spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: article_service_route
          uri: lb://article-service
          predicates:
            - Path=/as/**
          filters:
            - StripPrefix=1

server:
  port: 9000

management:
  endpoints:
    web:
      exposure:
        include: '*'